image: maven:3.3.9

pipelines:
  default:
    - step:
        deployment: production
        caches:
          - maven
        script:
          - mkdir -p ~/.ssh
          - (umask 077 ; echo $SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
          - mvn -B deploy -P bitbucket
